services:
  web:
    volumes:
     - .:/app 
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition : healthy
    env_file:
      - .env
    command: >
      /start

  postgres:
    image : postgres:latest
    restart: always
    ports:
      - 5432:5432
    volume:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5



volumes:
  postgres_data:
